* Ruby Treesitter mode
:PROPERTIES:
:PACKAGE: ruby-ts-mode
:END:

** Config :config:

Custom Ruby eval function for Navi

#+BEGIN_SRC emacs-lisp
(defun navi-eval:ruby-ts-mode (code)
  (comint-send-string (inf-ruby-proc) (format "%s\n" (string-trim-right code) ))
  (save-excursion
    (forward-line 1)
    (inf-ruby--eval-overlay
     (ruby-print-result-value))))

(defun kwrooijen/ruby-eval-and-return (code)
  "Send CODE to the inferior Ruby process and return the result.
To prevent the inferior Ruby process buffer from being polluted,
we store the buffer content in a temporary buffer, send the code
to the inferior Ruby process, and then return the result. Then we
restore the inferior Ruby process buffer to its original state."
  (let ((temp-buffer (generate-new-buffer "ruby-eval")))
    (with-current-buffer (process-buffer (inf-ruby-proc))
      (copy-to-buffer temp-buffer (point-min) (point-max))
      (comint-send-string (inf-ruby-proc) (format "%s\n" (string-trim code)))
      (let ((result (ruby-print-result-value))
            (inhibit-read-only t))
        (replace-buffer-contents temp-buffer)
        (kill-buffer temp-buffer)
        result))))
#+END_SRC

Require inf ruby

#+BEGIN_SRC emacs-lisp
(require 'inf-ruby)
#+END_SRC

** Bindings :general:

#+BEGIN_SRC emacs-lisp
(:keymaps 'ruby-ts-mode-map
          "M-a" 'navi-back-to-indentation)
#+END_SRC

** Hook :hook:

#+BEGIN_SRC emacs-lisp
(ruby-ts-mode . electric-indent-mode)
#+END_SRC


* Ruby mode
:PROPERTIES:
:PACKAGE: ruby-mode
:END:

** Hook :hook:

If we enter Ruby mode, switch to ruby-ts-mode.

#+BEGIN_SRC emacs-lisp
(ruby-mode . ruby-ts-mode)
#+END_SRC

** Init :init:

Remap ruby-mode to ruby-ts-mode to make use of Treesitter.

#+BEGIN_SRC emacs-lisp
(add-to-list 'major-mode-remap-alist '(ruby-mode . ruby-ts-mode))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun kwrooijen/rails-routes ()
  "Find the rails route based on a search string"
  (interactive)
  (let ((search-string (read-string "Search string: ")))
    (async-shell-command (concat "rails routes | grep " search-string))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun kwrooijen/rails-create-stimulus-controller (name)
  "Create a Stimulus controller in the current Rails project.
Given a NAME, this function creates a new Stimulus controller in the
app/javascript/controllers directory of the current Rails project.
"
  (interactive "sStimulus Controller name: ")
  (let ((controller-name (concat name "_controller.js"))
        (controller-dir (expand-file-name "app/javascript/controllers" (projectile-project-root))))
    (unless (file-directory-p controller-dir)
      (make-directory controller-dir t))
    (with-temp-file (expand-file-name controller-name controller-dir)
      (insert "import { Controller } from \"@hotwired/stimulus\"

export default class extends Controller {
  static values = {}
  static classes = [];
  static targets = [];

  connect() {
  }

  disconnect() {
  }
}"))
    (find-file (expand-file-name controller-name controller-dir))))
#+END_SRC


** Bindings :general:
#+BEGIN_SRC emacs-lisp
(kwrooijen/leader
  "c r c" 'kwrooijen/rails-create-stimulus-controller)
#+END_SRC


* Inferior Ruby
:PROPERTIES:
:PACKAGE: inf-ruby
:STRAIGHT: t
:END:

https://github.com/nonsequitur/inf-ruby

inf-ruby provides a REPL buffer connected to a Ruby subprocess.

** Init :init:
#+BEGIN_SRC emacs-lisp
(defun kwrooijen/ruby-rdbg ()
  (interactive)
  (if (get-buffer "*rdbg*")
      (switch-to-buffer "*rdbg*")
    (inf-ruby-console-run (format "rdbg -An") "rdbg")))
#+END_SRC

** Config :config:

Start the inf ruby console at the root of the rails project

#+BEGIN_SRC emacs-lisp
(defun inf-ruby-console-rails-from-project-root ()
  (interactive)
  (inf-ruby-console-rails (projectile-project-root)))
#+END_SRC

Locally remove underlines from the Inf-Ruby buffers to make it less
chaotic.

#+BEGIN_SRC emacs-lisp
(defun kwrooijen/inf-ruby-remove-underline ()
  (face-remap-add-relative 'underline :underline nil))
#+END_SRC

** Bindings :general:
#+BEGIN_SRC emacs-lisp
(kwrooijen/local-leader
  :keymaps 'ruby-ts-mode-map
  :states 'normal
  "'" 'inf-ruby
  ";" 'kwrooijen/ruby-rdbg
  "r" 'inf-ruby-console-rails-from-project-root
  "i s" 'ruby-switch-to-inf
  "i j" 'ruby-send-line
  "b b" 'ruby-switch-to-inf)
#+END_SRC

** Hook :hook:
#+BEGIN_SRC emacs-lisp
(inf-ruby-mode . kwrooijen/inf-ruby-remove-underline)
#+END_SRC


* Ruby Robe
:PROPERTIES:
:PACKAGE: robe
:STRAIGHT: t
:END:

https://github.com/dgutov/robe

Robe is a code assistance tool that uses a Ruby REPL subprocess with
your application or gem code loaded, to provide information about
loaded classes and modules, and where each method is defined.

** Hook :hook:

#+BEGIN_SRC emacs-lisp
((ruby-mode-hook . 'robe-mode)
 (inf-ruby-mode-hook . 'robe-mode)
 (inf-ruby-mode-hook . 'robe-start))
#+END_SRC

** Config :config:

Add Robe to company backends

#+BEGIN_SRC emacs-lisp
(eval-after-load 'company '(push 'company-robe company-backends))
#+END_SRC

** Bindings :general:

#+BEGIN_SRC emacs-lisp
(:states 'normal
         "s-<return>" 'robe-jump)
#+END_SRC


* Chruby
:PROPERTIES:
:PACKAGE: chruby
:STRAIGHT: t
:END:

** Hook :hook:

#+BEGIN_SRC emacs-lisp
(ruby-mode-hook . 'chruby-use-corresponding)
#+END_SRC
